### PR TITLE
Removing unnecessary files

### PR DESCRIPTION
**Pull request by prudhvi**
`sbt run` fails with these files being present as they are not needed for finatra branch.

@fneves

### CODE REVIEW

**Comment by fneves** [comment]
👍

**Comment by fneves** [comment]
Thanks for fixing this. This was just a dirty repo where I could dump all my stuff.

**Comment by prudhvi** [comment]
I was about to add akka-http branch for my finatra vs akka-http benchmark story so just cleaned up.

**Comment by prudhvi** [comment]
https://github.com/prudhvi/benchmarking/pull/2

**Pull request merged**
